In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
df=pd.read_csv('property_listing_data_in_Bangladesh.csv')

In [6]:
df.drop(['title','flooPlan','url','lastUpdated'],axis=1,inplace=True)

In [7]:
df['area']=df['area'].str.split(' ').str[0]

In [8]:
df['location']=df['adress'].str.split(',').str[1]

In [58]:
df['City']=df['adress'].str.split(',').str[2]

In [59]:
df.drop('adress',axis=1,inplace=True)

In [60]:
df['price']=df['price'].str.split(' ').str[0]

In [61]:

df['price'] = pd.to_numeric(df['price'])

In [62]:
df['price']=df['price']*1000

In [63]:
df['area'] = df['area'].str.replace(',', '')

In [9]:
df.head()

,beds,bath,area,adress,type,purpose,price,location
0,3,4,"2,200","Block A, Bashundhara R-A, Dhaka",Apartment,For Rent,50 Thousand,Bashundhara R-A
1,3,4,"1,400","South Khulshi, Khulshi, Chattogram",Apartment,For Rent,30 Thousand,Khulshi
2,3,4,"1,950","Block F, Bashundhara R-A, Dhaka",Apartment,For Rent,30 Thousand,Bashundhara R-A
3,3,3,"2,000","Sector 9, Uttara, Dhaka",Apartment,For Rent,35 Thousand,Uttara
4,3,4,"1,650","Block I, Bashundhara R-A, Dhaka",Apartment,For Rent,25 Thousand,Bashundhara R-A

In [65]:
df['location'].unique()

array([' Bashundhara R-A', ' Khulshi', ' Uttara', ' Gulshan',
       ' Chattogram', ' Chowdhuripara', ' Dhaka', ' Baridhara', ' Mirpur',
       ' Mohanagar Housing', ' South Khulshi', ' Dhaka Uddan',
       ' Mohammadpur', ' Section 2', ' North Khulshi', ' Katashur',
       ' Turag', ' Bochila City Developers Ltd', ' Pallabi',
       ' Colonel Hat', ' Chandrima Model Town', ' Badda', ' Motijheel',
       ' Kaderabad Housing Society', ' Section 11', ' Sector 13',
       ' Maghbazar', ' Dhanmondi', ' East Nasirabad', ' Khilkhet',
       ' Ahmed Nagar', ' Block E', ' Dakshin Khan', ' Section 12',
       ' Rampura', ' Mirpur DOHS', ' Sector 7', ' West Khulshi',
       ' Section 13', ' Section 10', ' Malibagh',
       ' 9 No. North Pahartali Ward', ' Section 6', ' Adabor',
       ' Banasree', ' Sector 4', ' Lalbagh', ' Merul Badda', ' Section 3',
       ' 12 No. Sarai Para Ward', ' Mansurabad Housing Society',
       ' Sat Masjid Housing', ' Shekhertek', ' Cantonment', ' Manikdi',
       ' 15 No. Bagmoniram Ward', ' Sugandha Residential Area',
       ' Sutrapur', ' Aftab Nagar', ' Tejgaon', ' Bayazid',
       ' Lal Khan Bazaar', ' Sector 6', ' Muradpur', ' Eskaton',
       ' Section 1', ' Hazaribag', ' Panchlaish',
       ' Halishahar Housing Estate', ' Nobodoy Housing Society',
       ' Pirerbag', ' Ibrahimpur', ' Block A', ' Bandar', ' Section 5',
       ' South Banasree Project', ' Double Mooring',
       ' Chad Uddan Housing', ' aziz Moholla',
       ' 16 No. Chawk Bazaar Ward', ' 1 No. South Pahartali Ward',
       ' 10 No. North Kattali Ward', ' Block K',
       ' 14 No. Lalkhan Bazaar Ward', ' 19 No. South Bakalia Ward',
       ' Sector 10', ' Rajuk Uttara Apartment Project', ' Niketan',
       ' Block F', ' 24 No. North Agrabad Ward', ' Kawlar', ' Lalmatia',
       ' Block C', ' 25 No. Rampur Ward', ' Agargaon', ' West Agargaon',
       ' Nikunja', nan, ' South Pirerbag', ' 22 No. Enayet Bazaar Ward',
       ' Halishahar', ' Block H', ' South Agrabad',
       ' 11 No. South Kattali Ward', ' Taltola', ' New Market',
       ' Block G', ' Nasirabad', ' Bochila Garden City', ' Badurtala',
       ' Raufabad Residential Area', ' Kaibalyadham Housing Society',
       ' Jalalabad Housing Society', ' Khilgaon', ' Dakshin Kattali',
       ' Kolpolok R/A', ' Arakan Housing Society', ' Sholokbahar',
       ' Faydabad', ' Dakkhin Paikpara', ' Dolipara',
       ' 40 No. North Patenga Ward', ' Bandartila', ' Block L',
       ' 39 No. South Halishahar Ward', ' Bakalia', ' Bashabo',
       ' Block B', ' 30 No. East Madarbari Ward', ' Hill View R/A',
       ' Mohakhali', ' Chadra Nagar', ' Munir Nagar', ' East Rampur',
       ' Chandgaon Residential Area', ' Block D', ' Pahartali',
       ' 23 No. North Pathantooly Ward', ' 36 Goshail Danga Ward',
       ' Somobay Residential Area', ' 7 No. West Sholoshohor Ward',
       ' 26 No. North Halishahar Ward', ' Chotopole', ' Jamal Khan',
       ' 3 No. Panchlaish Ward', ' Shah Ali Bag',
       ' 28 No. Pathantooly Ward', ' Sector 12', ' Aturar Depo',
       ' Rahman Nagar', ' Oxygen', ' Chawk Bazar', ' 4 No Chandgaon Ward',
       ' West Rampura', ' Paikpara', ' East Rampura',
       ' 18 No. East Bakalia Ward', ' Sher- E- Banglanagar',
       ' East Azampur', ' Eastern Housing', ' Goran', ' Middle Badda',
       ' Polytechnic', ' Kotwali', 'D. I. T. Project', ' Sector 15',
       ' Gawair', ' 37 No. North-Middle Halishahar Ward', ' Foys Lake',
       ' Notunbag', ' Namapara', ' Shahid Nagar', ' Kalachandpur',
       ' K. B. Aman Ali Road', ' Dewanhat', ' Kallyanpur',
       ' 38 No. South Middle Halishahar', ' Rupnagar Residential Area',
       ' Hathazari', ' CDA Residential Area', ' Tilpapara', ' Sayednagar',
       ' Kathgar', ' Uttar Badda', ' Baluchara', ' Uttar Khan',
       ' Muzaffarnagar Residential Area', ' 6 No East Sholoshohor Ward',
       ' Hossain Ahmed Para', ' Bochila', ' Sarulia', ' Jatra Bari',
       ' Patenga', ' Rongipara', ' 27 No. South Agrabad Ward',
       ' Bashundhara Residential Area', ' Shyamoli', ' Ashkona',
       ' Tejgaon Industrial Area', ' Shahjahanpur', ' Khilbari Tek',
       ' Vatara', ' Bahaddarhat', ' Muslimabad', ' Ali Nagar',
       ' Natun Bazar', ' South Khulshi Residential Area', ' Sabujbag',
       ' Middle Pirerbag', ' Borobag', ' Boro Maghbazar'], dtype=object)

In [66]:
df=pd.get_dummies(df, columns = ['type','City'])

In [67]:
data=pd.DataFrame(df)

In [68]:
data['City_ Sholokbahar'].value_counts

<bound method IndexOpsMixin.value_counts of 0       False
1       False
2       False
3       False
4       False
        ...
7552    False
7553    False
7554    False
7555    False
7556    False
Name: City_ Sholokbahar, Length: 7557, dtype: bool>

In [69]:
from sklearn.preprocessing import LabelEncoder

In [70]:
le=LabelEncoder()

In [71]:
data['location']=le.fit_transform(data['location'])

In [72]:
data['beds']=le.fit_transform(data['beds'])

In [73]:
data['bath']=le.fit_transform(data['bath'])

In [74]:
data.drop('purpose',axis=1,inplace=True)

In [75]:
data.head(30)

,beds,bath,area,price,location,type_Apartment,type_Building,type_Duplex,City_ 10 No. North Kattali Ward,City_ 11 No. South Kattali Ward,...,City_ Sholokbahar,City_ South Agrabad,City_ South Khulshi,City_ South Khulshi Residential Area,City_ Taltola,City_ Tejgaon,City_ Uttara,City_ Wazedia,City_ West Agargaon,City_ West Rampura
0,6,4,2200,50000.0,45,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,6,4,1400,30000.0,115,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,6,4,1950,30000.0,45,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,6,3,2000,35000.0,203,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,6,4,1650,25000.0,45,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,10,5,3400,1100.0,93,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,6,3,1600,35000.0,203,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,6,3,1250,23000.0,45,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,6,4,2150,40000.0,203,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,6,3,1250,23000.0,45,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,6,3,1250,23000.0,45,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,6,3,1580,20000.0,69,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,9,4,3200,2500.0,93,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,6,3,3000,1200.0,93,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,6,3,1250,21000.0,45,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,6,4,1800,60000.0,203,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,6,3,1250,21000.0,45,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,6,3,2000,40000.0,45,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,6,4,1750,30000.0,45,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,6,3,1250,23000.0,45,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,6,3,1250,23000.0,45,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,6,3,1310,28000.0,72,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,6,3,1250,21000.0,45,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,6,4,2200,60000.0,203,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,6,4,1700,75000.0,78,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,9,4,2750,1200.0,78,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,6,2,1400,28000.0,78,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,9,4,2500,55000.0,43,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,0,0,550,12000.0,128,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,6,2,1050,21000.0,132,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [76]:
data['location'].value_counts()

location
78     1085
203     960
128     452
69      407
45      302
       ...
63        1
91        1
160       1
90        1
61        1
Name: count, Length: 211, dtype: int64

In [77]:
data=data*1

In [78]:
data.head()

,beds,bath,area,price,location,type_Apartment,type_Building,type_Duplex,City_ 10 No. North Kattali Ward,City_ 11 No. South Kattali Ward,...,City_ Sholokbahar,City_ South Agrabad,City_ South Khulshi,City_ South Khulshi Residential Area,City_ Taltola,City_ Tejgaon,City_ Uttara,City_ Wazedia,City_ West Agargaon,City_ West Rampura
0,6,4,2200,50000.0,45,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,6,4,1400,30000.0,115,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,4,1950,30000.0,45,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,6,3,2000,35000.0,203,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,6,4,1650,25000.0,45,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [79]:
y=data.iloc[:,3:4]

In [80]:
X=data.drop('price',axis=1)

In [81]:
X

,beds,bath,area,location,type_Apartment,type_Building,type_Duplex,City_ 10 No. North Kattali Ward,City_ 11 No. South Kattali Ward,City_ 12 No. Sarai Para Ward,...,City_ Sholokbahar,City_ South Agrabad,City_ South Khulshi,City_ South Khulshi Residential Area,City_ Taltola,City_ Tejgaon,City_ Uttara,City_ Wazedia,City_ West Agargaon,City_ West Rampura
0,6,4,2200,45,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,6,4,1400,115,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,4,1950,45,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,6,3,2000,203,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,6,4,1650,45,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7552,9,4,3600,203,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7553,6,2,900,203,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7554,2,2,1000,203,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7555,6,4,3600,93,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7556,9,4,2600,78,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [82]:
from sklearn.model_selection import train_test_split

In [98]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [100]:
from sklearn.ensemble import RandomForestRegressor

In [104]:

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

# Define the model
model = RandomForestClassifier(n_estimators= 100, min_samples_split=5, min_samples_leaf=1, max_depth=30, criterion='gini',bootstrap=False)

# Define parameter distributions
param_distributions = {
    'n_estimators': [10, 50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False],
    'criterion': ['gini', 'entropy']  # Valid criteria for classifiers
}

# Create the RandomizedSearchCV object
rcv = RandomizedSearchCV(model, param_distributions=param_distributions, n_iter=10, scoring='accuracy', random_state=42)

# Fit the RandomizedSearchCV
rcv.fit(X_train, y_train)

# Access the best parameters
best_params = rcv.best_params_

# Display the best parameters
print("Best Parameters:", best_params)

D:\anaconda\Lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Best Parameters: {'n_estimators': 100, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_depth': 30, 'criterion': 'gini', 'bootstrap': False}

In [105]:
model.fit(X_train,y_train)

D:\anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(bootstrap=False, max_depth=30, min_samples_split=5)

In [108]:
y_pred=model.predict(X_test)

In [110]:
from sklearn.metrics import accuracy_score

In [111]:
a=accuracy_score(y_test,y_pred)

In [112]:
print (a)

0.32076984763432237

In [116]:
b=model.score(X_train,y_train)

In [117]:
print(b)

0.6474422279281059

In [118]:
import pickle

In [119]:
# Save the model to a file
with open('model.pkl', 'wb') as file:
    pickle.dump(model, file)